# Generated by Django 5.2.8 on 2025-12-07 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borne_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('current_state', models.CharField(choices=[('ATTENTE_LOGIN', 'Attente connexion'), ('MENU_PRINCIPAL', 'Menu principal'), ('PASS_CHOIX_PRODUIT', 'Choix produit PASS'), ('PASS_CHOIX_RECURRENCE', 'Choix récurrence'), ('PASS_COLLECTE_NOM', 'Collecte nom'), ('PASS_COLLECTE_PRENOM', 'Collecte prénom'), ('PASS_COLLECTE_TELEPHONE', 'Collecte téléphone'), ('PASS_COLLECTE_NAISSANCE', 'Collecte date naissance'), ('PASS_AJOUT_BENEFICIAIRE', 'Ajout bénéficiaire'), ('PASS_CONFIRMATION', 'Confirmation'), ('COMMISSIONS_MENU', 'Menu commissions'), ('SIMULATEUR_CHOIX', 'Choix produit simulateur'), ('SIMULATEUR_COLLECTE', 'Collecte infos prospect')], default='ATTENTE_LOGIN', max_length=50)),
                ('context', models.JSONField(default=dict, help_text='Données temporaires conversation')),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='borne_auth.agent')),
            ],
            options={
                'db_table': 'whatsapp_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('direction', models.CharField(choices=[('incoming', 'Reçu'), ('outgoing', 'Envoyé')], max_length=10)),
                ('message_type', models.CharField(max_length=20)),
                ('content', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bot.whatsappsession')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
